{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.satellite.reactor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-drbd-reactor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName }}-drbd-reactor
    {{- with .Values.satellite.reactor.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.satellite.reactor.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9942
  selector:
    app: {{ $fullName }}-satellite
{{- end }}