{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.reactor.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-drbd-reactor
  namespace: {{ .Release.Namespace }}
data:
  drbd-reactor.toml: |+
    snippets = "/etc/drbd-reactor.d"
    statistics-poll-interval = {{ .Values.reactor.pollInterval }}
    [[log]]
    level = "info"
    file = "/dev/stdout"
    [[prometheus]]
    enums = true
    address = "0.0.0.0:{{ .Values.reactor.port }}"
{{- end }}